name: OpenFilesLeakDebugger
main: dktapps\OpenFilesLeakDebugger\Main
version: 0.1.0
api: 3.0.0
load: STARTUP
author: dktapps
description: Debugger for file descriptor leaks
website: https://github.com/dktapps/OpenFilesLeakDebugger
